### ISSUE TITLE
Странная конкатенация строки в итераторе цикла

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#13]
https://github.com/Cmanka/Practice/blob/d20fdab982aef149170ebfc8865bbabd86dd9dca/PR1/Script.cs#L90

к тому же есть padleft - https://docs.microsoft.com/en-us/dotnet/api/system.string.padleft?view=netcore-3.1, padright и т.п.
"".PadLeft(3, '_')

**Comment by Cmanka** [comment]
![image](https://user-images.githubusercontent.com/46560544/85426698-7cf51080-b583-11ea-8838-7dfc977b53fa.png)
Изменил конкатенацию строки
