### ISSUE TITLE
По заданию просили непробитые на сайте номера записывать в файл и пропускать из обработки номера, если файлы лежат в папке.

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#14]
https://github.com/Cmanka/Practice/blob/d20fdab982aef149170ebfc8865bbabd86dd9dca/PR1/Script.cs#L300

а здесь записывается в файл просто если в папке нет файла.
соответствено нужно сравнивать название файла с номером в нормализованном виде

**Comment by Cmanka** [comment]
![image](https://user-images.githubusercontent.com/46560544/85424485-a8c2c700-b580-11ea-826f-d65ef87051da.png)
В параметре номер, который мы собираемся пробивать. Вернет тру, если найдет его в папке.
![image](https://user-images.githubusercontent.com/46560544/85424697-e889ae80-b580-11ea-8c22-dfe550ca209f.png)
Условие, если вернет отрицательное значение значит элемент не найден в папке и значит номер ниразу не пробивался.
![image](https://user-images.githubusercontent.com/46560544/85424868-1ff85b00-b581-11ea-9538-de3c54c33d04.png)
Выдаст ошибку, что номер, который хотите пробить уже в файле с плохие номера(которые не пробились) или же в папке картинок.

**Comment by Cmanka** [comment]
![image](https://user-images.githubusercontent.com/46560544/85425341-bcbaf880-b581-11ea-95ed-5b9842ac1540.png)
Одно из условий, когда непробитый номер записывается в файл плохих номеров

**Comment by Alex-Alimerzaev** [comment]
sw.Close не нужен, using все закроет

**Comment by Alex-Alimerzaev** [comment]
Уже прямым тесктом сказано убрать из CheckNumber badNumbersFilePath
