### ISSUE TITLE
Не могу понять, почему при скачке фотографий их больше чем надо, хотя до этого всё было нормально.

### ISSUE THREAD

**Issue by Cmanka** [Cmanka/Practice#16]
![image](https://user-images.githubusercontent.com/46560544/85555519-adde4f80-b62e-11ea-9931-c225512b7772.png)
Получаю img со страницы с данным классом
![image](https://user-images.githubusercontent.com/46560544/85556026-2218f300-b62f-11ea-8856-9605ab74ae99.png)
Image.Count = 5 хотя до всего было 2 как и должно быть(если 2 фотографии, с единичными фотографиями проблем нету)

**Comment by Alex-Alimerzaev** [comment]
Нужно скачать все фотографии. Хоть 10, их нужно скачать. Все что на странице есть.
