### ISSUE TITLE
Странные аббревиатуры, переменные дожны называться осмысленно и понятно

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#18]
https://github.com/Cmanka/Practice/blob/083e06362094bc98b2eb9fb07f9c09cec4b1555a/PR1/Script.cs#L27

**Comment by Cmanka** [comment]
Ну я рассчитывал, что этих сокращенний будет достаточно(fp-filePath), но по всей видимости нет. 
![image](https://user-images.githubusercontent.com/46560544/85665280-e7ad6580-b6c3-11ea-983d-5e3de1aa7a56.png)
