### ISSUE TITLE
NormalizeNumbers

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#2]
https://github.com/Cmanka/Practice/blob/d516c40f62233ee1d589e52211662520b2900cb4/PR1/Program.cs#L18
странный метод нормализации
1) можно regex-ом удалить символы отличные от буквы/цифры
2) никто не говорил, что их нужно записывать в новый файл
3) для простоты нужно еще в регистр один ривести, например tolower

**Comment by Alex-Alimerzaev** [comment]
https://github.com/Cmanka/Practice/blob/d20fdab982aef149170ebfc8865bbabd86dd9dca/PR1/Script.cs#L278

А можешь сделать такой?
public static string NormalizeNumber(string number)
и использовать его по месту в алгоритме, а не плодить еще один файл и его открывать
у тебя есть один файл с номерами. 
открыл его, и в цикле читаешь строки, и соответственно для строки вызываешь NormalizeNumber, вот у тебя уже и есть нормализованный номер.

Соответственно, на странице с описанием нашел контейнер, где лежит номер, получил текст, вызвал NormalizeNumber, вот еще один нормализованный номер со страницы. И их сравнил, совпадают они, значит качаем картинку, нет - идем на следующий номер

**Comment by Cmanka** [comment]
![image](https://user-images.githubusercontent.com/46560544/85426381-1112a800-b583-11ea-87b2-9fd5cf144c04.png)
Новый метод.
![image](https://user-images.githubusercontent.com/46560544/85426425-1ff95a80-b583-11ea-8b0d-18e295c64760.png)
Использование метода.

**Comment by Alex-Alimerzaev** [comment]
регулярка неправильная
\W+ надо использовать
