### ISSUE TITLE
ErrorMessage не соответствует действительности

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#21]
`public static void ErrorMessage()
        {
            Console.WriteLine("Enter arguments " +
                    "*args[0] = file Path, " +
                    "*args[1] = folder for images, " +
                    "*args[2] = folder for ready images, " +
                    "args[3] = max side size image, " +
                    "args[4] = quality of the image, " +
                    "*args[5] = file for bad numbers, " +
                    "*args[6] = name of the producer");
        }`

к тому же это справка, а не ErrorMessage

**Comment by Cmanka** [comment]
![image](https://user-images.githubusercontent.com/46560544/85665411-0c094200-b6c4-11ea-8026-5b7cfe30c061.png)

**Comment by Alex-Alimerzaev** [comment]
что такое args[0]?
Открой справку по какой нибудь консоли и посмотри

например git
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

вот так должно выглядеть
