### ISSUE TITLE
Смысл скроллить?

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#22]
https://github.com/Cmanka/Practice/blob/083e06362094bc98b2eb9fb07f9c09cec4b1555a/PR1/Script.cs#L99
Без скроллинга никак?

**Comment by Cmanka** [comment]
Я ставлю настройку --headless, и у меня отрабатывает только консоль, и в одном месте, чтобы избежать ошибки скролю вниз.(Если эту настройку убрать можно и без скрола)
