### ISSUE TITLE
Script.cs содержит разношерстные классы

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#23]
1 класс - 1 файл в идеале должны быть

**Comment by Cmanka** [comment]
То что я по папкам не расскидывал, а просто закинул всё до одной кучи, это же не важно?

**Comment by Alex-Alimerzaev** [comment]
Ну сканеры можно и в отдельную папку.

**Comment by Cmanka** [comment]
Вы там посмотрите, если найдете ещё какие-то косяки, то следующим коммитом их в папку закину.
