### ISSUE TITLE
Отсутствует 'Accept-Encoding': 'identity'

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#25]
https://github.com/Cmanka/Practice/blob/c2ded9b1b646d720f9b490f5e68ef189daa0da6f/PR1/Script.cs#L55
и отсутствует проверка, что файл доступен (response пришел со статусом 200).

**Comment by Cmanka** [comment]
Сделал проверку на response и указал в headers accept-encoding:identity(Method DownloadImage)
