### ISSUE TITLE
Странная проверка входных параметров

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#29]
https://github.com/Cmanka/Practice/blob/c2ded9b1b646d720f9b490f5e68ef189daa0da6f/PR1/Program.cs#L83

валидация сработает, когда передан кривой параметр
а получается не передать файл с номерами, папку куда файлы складывать и т.п., то произойдет запуск алгоритма сканирования, что в корне не верно

**Comment by Cmanka** [comment]
Надеюсь правильно понял и в модели поставил условия в мутаторах. И поставил условие на четность кол-во элементов т.к если указать нечетное количество выдаст исключение.(Элементы за ренжой массива)
