### ISSUE TITLE
Помимо xpath есть css selector

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#7]
https://github.com/Cmanka/Practice/blob/d516c40f62233ee1d589e52211662520b2900cb4/PR1/Program.cs#L98

**Comment by Cmanka** [comment]
Не посчитал важным менять поиск, т.к почитав пару статей, понял что на повышенние производительности не как не сказывается(По большей части).

**Comment by Alex-Alimerzaev** [comment]
Учись работать с css селекторами, на frontend не будет  xpath
