### ISSUE TITLE
Нет сравнения пробиваемого номера с тем что пришло в резульатах

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#8]
https://github.com/Cmanka/Practice/blob/d516c40f62233ee1d589e52211662520b2900cb4/PR1/Program.cs#L106

Прежде чем обрабатывать картинки, нужно сравнить номер, с тем что пробили, номера в нормализованном виде.
Потому что иногда вылазят аналоги или заменители, и ты можешь скопировать картинку, выдавая ее на пробиваемую по номеру, а это не совсем так.

![изображение](https://user-images.githubusercontent.com/67115251/85055681-9de5ec00-b1a6-11ea-80a0-04b4394364d6.png)

**Comment by Cmanka** [comment]
Булевый метод CheckNumber и в методе ParseData реализуется проверка

**Comment by Alex-Alimerzaev** [comment]
CheckNumber это поиск по файлам, другого не вижу.

В первом топике показал какой номер должен сравниваться с пробиваемым, разумеется в нормализованном виде эти номера сравниваются. Такого сравнения не увидел

**Comment by Cmanka** [comment]
![image](https://user-images.githubusercontent.com/46560544/85425684-2935f780-b582-11ea-9028-654d9333f36d.png)
Этого разве недостаточно? Поиск элементов на странице с моим нормализованным номером из файла, если элемент такой, то коунт будет более нуля и соответственно по LinkText(line) пробъем данный номер, в противном случае просто ничего не находится и заносится в файл непробитых номеров.
![image](https://user-images.githubusercontent.com/46560544/85425904-774afb00-b582-11ea-92de-aa1a7a1b654d.png)

**Comment by Alex-Alimerzaev** [comment]
не достаточно

$"{line}" - смысл этого форматирования? если в результате строка не меняется

**Comment by Cmanka** [comment]
$"{line}" -  это просто я передаю нормализованный номер, который берется файла и на странице по LinkText пробивается наш номер(Если пробивается, если нет то каунт меньше и номер в неуспешный файл).

**Comment by Alex-Alimerzaev** [comment]
Зачем здесь используется форматирование строки?
$"{line}" => string.Format("{0}", line) 
Не вижу смыла такое делать если в результате $"{line}" == line

**Comment by Cmanka** [comment]
Справедливо, согласен, убрал.
