### ISSUE TITLE
А где стратегия?

### ISSUE THREAD

**Issue by Alex-Alimerzaev** [Cmanka/Practice#9]
https://github.com/Cmanka/Practice/blob/d516c40f62233ee1d589e52211662520b2900cb4/PR1/Program.cs#L287

Нет стратегии. Каждый алгоритм сканирования поместить в отдельный файл. 
1 производитель  - 1 алгоритм - 1 файл
При вызове exe-шника определить какой производитель пришел в параметрах, инициализировать нужный экземпляр класса и запустить на выполнение алгоритм.

**Comment by Cmanka** [comment]
Разобрался с паттерном стратегия, но не понял как на сайте, котором осуществляю парс, осуществить связь с производителем.
![image](https://user-images.githubusercontent.com/46560544/85228309-7469d200-b3eb-11ea-922a-6d20554e090d.png), есть предположение, что должна быть заготовленна пачка производителей для запуска алгоритма с производителеми и из скрина, который выше, брать ключ и сравнивать и таким образом получать нужную деталь.

**Comment by Alex-Alimerzaev** [comment]
Будет несколько производителей, и для них отдельные сайты. Твоя программа должна уметь понимать, какой производитель пришел в параметрах запуска, и соответственно по этому производителю выбрать нужный алгоритм для парсинга.

**Comment by Cmanka** [comment]
Так под словом производитель, вы имеете ввиду сайт, который поставляет запчасти?

**Comment by Alex-Alimerzaev** [comment]
Под словом производитель имеется ввиду название компании, которая производит запчасти. Bosch, Stellox, Wabco и т.д.
И с этим названием должен быть связан алгоритм по сканированию.

**Comment by Cmanka** [comment]
Я как бы реализовал сам паттерн, но полную реализацию для парса другого сайта не делал, потому что до конца не могу понять, то ли я вообще делаю, если использовать имена производитилей запчастей, то как вообще это скрещивать в проекте, я никак не могу сформировать в голове это. А если брать за суть то, что ты меняешь парс в засимости от сайта, то это в принципе я и сделал.

**Comment by Alex-Alimerzaev** [comment]
У тебя есть произвордитель Sachs под него ты делаешь SachsScanner класс,
Для Bosch - BoschScanner и т.д.
У сканеров есть интерфейс IManufacturerScanner c одним методом void Scan(Settings settings)
Где в Settings лежат настройки файлов и куда складывать картинки и кака их обрабатывать.

соответственно когда в параметрах приходит Sachs то создается экземпляр SachsScanner и запускается на выполнение посредством вызова метода Scan()

Впринципе как твои IParse только непонятно, что это совсем. И названия AfterMarket и PartsFinder некорректны
